function RatingNetworkDatahighlowtemp = importfile(filename, dataLines)
%IMPORTFILE Import data from a text file
%  RATINGNETWORKDATAHIGHLOWTEMP = IMPORTFILE(FILENAME) reads data from
%  text file FILENAME for the default selection.  Returns the data as a
%  table.
%
%  RATINGNETWORKDATAHIGHLOWTEMP = IMPORTFILE(FILE, DATALINES) reads data
%  for the specified row interval(s) of text file FILENAME. Specify
%  DATALINES as a positive scalar integer or a N-by-2 array of positive
%  scalar integers for dis-contiguous row intervals.
%
%  Example:
%  RatingNetworkDatahighlowtemp = importfile("C:\Users\mdama\Desktop\Matteo\KramerLab\Paperforpublication\Predictionpaper\FinalPaper_NeuroImage\GitHubPost\RatingNetworkData_highlowtemp.csv", [2, Inf]);
%
%  See also READTABLE.
%
% Auto-generated by MATLAB on 02-May-2020 13:28:25

%% Input handling

% If dataLines is not specified, define defaults
if nargin < 2
    dataLines = [2, Inf];
end

%% Setup the Import Options
opts = delimitedTextImportOptions("NumVariables", 8);

% Specify range and delimiter
opts.DataLines = dataLines;
opts.Delimiter = ",";

% Specify column names and types
opts.VariableNames = ["subject", "rating", "C1", "C2", "C3", "C4", "temp", "painornopain"];
opts.VariableTypes = ["double", "double", "double", "double", "double", "double", "categorical", "categorical"];
opts = setvaropts(opts, [7, 8], "EmptyFieldRule", "auto");
opts.ExtraColumnsRule = "ignore";
opts.EmptyLineRule = "read";

% Import the data
RatingNetworkDatahighlowtemp = readtable(filename, opts);

end